"""add source_image_url to source_mappings

Revision ID: 2b350b0b23e2
Revises: 807568d3ebd3
Create Date: 2026-09-19 07:12:38.562772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b350b0b23e2'
down_revision: Union[str, None] = '807568d3ebd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_mappings', sa.Column('source_image_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_mappings', 'source_image_url')
    # ### end Alembic commands ###
