"""add ordered product/size/quantity to customer_orders

Revision ID: 304fd21af985
Revises: 2b350b0b23e2
Create Date: 2026-09-20 06:03:07.232238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304fd21af985'
down_revision: Union[str, None] = '2b350b0b23e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_orders', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('customer_orders', sa.Column('ordered_size', sa.String(length=16), nullable=False))
    op.add_column('customer_orders', sa.Column('quantity', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_customer_orders_product_id'), 'customer_orders', ['product_id'], unique=False)
    op.create_foreign_key(
        'fk_customer_orders_product_id_master_products', 'customer_orders', 'master_products', ['product_id'], ['product_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_customer_orders_product_id_master_products', 'customer_orders', type_='foreignkey')
    op.drop_index(op.f('ix_customer_orders_product_id'), table_name='customer_orders')
    op.drop_column('customer_orders', 'quantity')
    op.drop_column('customer_orders', 'ordered_size')
    op.drop_column('customer_orders', 'product_id')
    # ### end Alembic commands ###
