"""add vendor_item_ids_json to market_listings

Revision ID: 6fbccea313b8
Revises: 304fd21af985
Create Date: 2026-09-22 06:46:29.255773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fbccea313b8'
down_revision: Union[str, None] = '304fd21af985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='{}' 필요 — 이미 존재하는 market_listings 행들도 NOT NULL 컬럼을
    # 추가하려면 기존 행에 채울 기본값이 있어야 한다(자동생성 코드는 이를 빠뜨렸다).
    op.add_column(
        'market_listings',
        sa.Column(
            'vendor_item_ids_json',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_listings', 'vendor_item_ids_json')
    # ### end Alembic commands ###
