"""initial schema: master_products, source_mappings, generated_assets, market_listings, customer_orders, order_fulfillments, return_requests

Revision ID: 807568d3ebd3
Revises: 
Create Date: 2026-09-18 00:52:11.638621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '807568d3ebd3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_type', sa.Enum('NAVER_SMARTSTORE', 'COUPANG', 'GMARKET', 'TOSS', name='markettype'), nullable=False),
    sa.Column('market_order_id', sa.String(length=128), nullable=False),
    sa.Column('recipient_name', sa.String(length=64), nullable=False),
    sa.Column('recipient_phone', sa.String(length=32), nullable=False),
    sa.Column('shipping_addr', sa.String(length=512), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'SOURCING_IN_PROGRESS', 'ORDER_PURCHASED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_customer_orders_market_order_id'), 'customer_orders', ['market_order_id'], unique=True)
    op.create_table('master_products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('style_code', sa.String(length=64), nullable=False),
    sa.Column('brand_name', sa.String(length=128), nullable=False),
    sa.Column('product_name', sa.String(length=512), nullable=False),
    sa.Column('raw_specs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_master_products_style_code'), 'master_products', ['style_code'], unique=True)
    op.create_table('generated_assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ai_thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('ai_detail_image_url', sa.String(length=1024), nullable=True),
    sa.Column('exif_cleared', sa.Boolean(), nullable=False),
    sa.Column('generation_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='generationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['master_products.product_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_generated_assets_product_id'), 'generated_assets', ['product_id'], unique=False)
    op.create_table('market_listings',
    sa.Column('listing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('market_type', sa.Enum('NAVER_SMARTSTORE', 'COUPANG', 'GMARKET', 'TOSS', name='markettype'), nullable=False),
    sa.Column('market_product_id', sa.String(length=128), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SOLD_OUT', 'SUSPENDED', name='listingstatus'), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['master_products.product_id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_market_listings_product_id'), 'market_listings', ['product_id'], unique=False)
    op.create_table('order_fulfillments',
    sa.Column('fulfillment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('source_platform', sa.Enum('ABC_MART', 'MUSINSA', 'FOLDER', 'BRAND_OFFICIAL', 'OTHER', name='sourceplatform'), nullable=False),
    sa.Column('source_order_id', sa.String(length=128), nullable=True),
    sa.Column('cost_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('courier_code', sa.String(length=32), nullable=True),
    sa.Column('tracking_no', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['customer_orders.order_id'], ),
    sa.PrimaryKeyConstraint('fulfillment_id')
    )
    op.create_index(op.f('ix_order_fulfillments_order_id'), 'order_fulfillments', ['order_id'], unique=False)
    op.create_table('return_requests',
    sa.Column('return_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('market_claim_id', sa.String(length=128), nullable=True),
    sa.Column('claim_reason', sa.String(length=512), nullable=False),
    sa.Column('inspection_status', sa.Enum('RECEIVED_AT_WAREHOUSE', 'INSPECTION_PASSED', 'INSPECTION_FAILED', 'SOURCE_RETURN_REQUESTED', 'SOURCE_RETURN_COMPLETED', 'DISPUTE_INVESTIGATING', 'REFUND_COMPLETED', name='inspectionstatus'), nullable=False),
    sa.Column('source_refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['customer_orders.order_id'], ),
    sa.PrimaryKeyConstraint('return_id')
    )
    op.create_index(op.f('ix_return_requests_order_id'), 'return_requests', ['order_id'], unique=False)
    op.create_table('source_mappings',
    sa.Column('source_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_platform', sa.Enum('ABC_MART', 'MUSINSA', 'FOLDER', 'BRAND_OFFICIAL', 'OTHER', name='sourceplatform'), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('source_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('size_stock_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['master_products.product_id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_source_mappings_product_id'), 'source_mappings', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_mappings_product_id'), table_name='source_mappings')
    op.drop_table('source_mappings')
    op.drop_index(op.f('ix_return_requests_order_id'), table_name='return_requests')
    op.drop_table('return_requests')
    op.drop_index(op.f('ix_order_fulfillments_order_id'), table_name='order_fulfillments')
    op.drop_table('order_fulfillments')
    op.drop_index(op.f('ix_market_listings_product_id'), table_name='market_listings')
    op.drop_table('market_listings')
    op.drop_index(op.f('ix_generated_assets_product_id'), table_name='generated_assets')
    op.drop_table('generated_assets')
    op.drop_index(op.f('ix_master_products_style_code'), table_name='master_products')
    op.drop_table('master_products')
    op.drop_index(op.f('ix_customer_orders_market_order_id'), table_name='customer_orders')
    op.drop_table('customer_orders')
    # ### end Alembic commands ###
    # PostgreSQL ENUM 타입은 op.drop_table()로 자동 제거되지 않으므로 명시적으로 정리한다.
    for enum_name in (
        "markettype",
        "sourceplatform",
        "generationstatus",
        "listingstatus",
        "orderstatus",
        "inspectionstatus",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
