"""add shipment box and vendor item id to customer orders

Revision ID: eff421c900ba
Revises: 6fbccea313b8
Create Date: 2026-09-23 00:57:43.775140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff421c900ba'
down_revision: Union[str, None] = '6fbccea313b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_orders', sa.Column('market_shipment_box_id', sa.String(length=64), nullable=True))
    op.add_column('customer_orders', sa.Column('market_vendor_item_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_orders', 'market_vendor_item_id')
    op.drop_column('customer_orders', 'market_shipment_box_id')
    # ### end Alembic commands ###
